services:
  mysql:
    image: mysql
    container_name: mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    links:
      - mysql
    environment:
      PMA_HOST: mysql # Connects to the 'mysql' service defined above
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80" # Map container port 80 to host port 8080
    restart: always
volumes:
  mysql_data:
